#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

// Require the autoloader, we need this crazyness for global installations.
foreach ([__DIR__ . '/../../autoload.php', __DIR__ . '/../vendor/autoload.php', __DIR__ . '/vendor/autoload.php'] as $file) {
  if (file_exists($file)) {
    require_once $file;
    break;
  }
}

require_once __DIR__ . '/services.php';
require_once __DIR__ . '/events.php';

// Setup the app.
$app = new Application();
$commands = ['Status', 'Projects', 'Retry', 'Progress', 'SshKey', 'Build', 'Cancel'];
foreach ($commands as $command) {
  $class = sprintf('Circle\Command\%sCommand', $command);
  $app->add(new $class($container['circle'], $container['config'], $container['dispatcher']));
}
$app->run();
