#!/usr/bin/env php
<?php

use Symfony\Component\Console\Application;

// Require the autoloader.
require_once 'vendor/autoload.php';
require_once __DIR__ . '/services.php';
require_once __DIR__ . '/events.php';

// Setup the app.
$app = new Application();
$commands = ['Status', 'Projects', 'Retry', 'Progress', 'SshKey', 'Build', 'Cancel'];
foreach ($commands as $command) {
  $class = sprintf('Circle\Command\%sCommand', $command);
  $app->add(new $class($container['circle'], $container['config'], $container['dispatcher']));
}
$app->run();
